name: zanzibar.ourworld.tf
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on zanzibar.ourworld.tf
      uses: appleboy/ssh-action@master
      with:
        host: zanzibar.ourworld.tf
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/www_eden/
          git log -1
          git restore .
          git pull
          sed -i "s/https:\/\/www2.zanzibar.ourworld.tf/https:\/\/zanzibar.ourworld.tf/g" config.toml
          ./build.sh
